version = 1
SPDX-PackageName = "Feather-UI"
SPDX-PackageSupplier = "Fundament Software <https://fundament.software>"
SPDX-PackageDownloadLocation = "https://github.com/Fundament-Software/feathergui"

# Generated lock files.
[[annotations]]
path = [
	"*.lock",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Fundament Software SPC <https://fundament.software>"
SPDX-License-Identifier = "Apache-2.0"

# Config files that we can't comment in.
[[annotations]]
path = [
	".git-blame-ignore-revs",
	".luarc.json",
	".vscode/**/*.json",
]
precedence = "closest"
SPDX-FileCopyrightText = "2025 Fundament Software SPC <https://fundament.software>"
SPDX-License-Identifier = "Apache-2.0"

# Source/data files that we can't comment in.
[[annotations]]
path = [
	"testlist.json",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Fundament Software SPC <https://fundament.software>"
SPDX-License-Identifier = "Apache-2.0"

# Source/data files that we don't want to comment in.
[[annotations]]
path = [
	"*.alc",
	"test*.lua",
	"tests/*.alc",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Fundament Software SPC <https://fundament.software>"
SPDX-License-Identifier = "Apache-2.0"

# Generated source/data files that we don't want to comment in.
[[annotations]]
path = [
	"types/*.lua",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Fundament Software SPC <https://fundament.software>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/lpeg/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright © 2007-2023 Lua.org, PUC-Rio."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/luafilesystem/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright © 2010-2022 The LuaFileSystem authors. Copyright © 2003-2010 Kepler Project."
SPDX-License-Identifier = "MIT"
