version = 1
SPDX-PackageName = "Feather-UI"
SPDX-PackageSupplier = "Fundament Software <https://fundament.software>"
SPDX-PackageDownloadLocation = "https://github.com/Fundament-Software/feathergui"

[[annotations]]
path = "types/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Fundament Software SPC <https://fundament.software>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".vscode/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Fundament Software SPC <https://fundament.software>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/lpeg/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright © 2007-2023 Lua.org, PUC-Rio."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/luafilesystem/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright © 2010-2022 The LuaFileSystem authors. Copyright © 2003-2010 Kepler Project."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ".*"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Fundament Software SPC <https://fundament.software>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/*.alc"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Fundament Software SPC <https://fundament.software>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "*.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Fundament Software SPC <https://fundament.software>"
SPDX-License-Identifier = "Apache-2.0"


[[annotations]]
path = ".envrc"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Fundament Software SPC <https://fundament.software>"
SPDX-License-Identifier = "Apache-2.0"
