version = 1
SPDX-PackageName = "Feather-UI"
SPDX-PackageSupplier = "Fundament Software <https://fundament.software>"
SPDX-PackageDownloadLocation = "https://github.com/Fundament-Software/feathergui"

# Generated source/data files that we don't want to comment in.
[[annotations]]
path = "types/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Fundament Software SPC <https://fundament.software>"
SPDX-License-Identifier = "Apache-2.0"

# Config files that we can't or don't want to comment in.
[[annotations]]
path = [
	".*",
	".vscode/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Fundament Software SPC <https://fundament.software>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/lpeg/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright © 2007-2023 Lua.org, PUC-Rio."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/luafilesystem/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright © 2010-2022 The LuaFileSystem authors. Copyright © 2003-2010 Kepler Project."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["vendor/luajit2/src/lauxlib.h", "vendor/luajit2/src/lua.h"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) 1994-2008 Lua.org, PUC-Rio.  All rights reserved."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["vendor/luajit2/src/luaconf.h", "vendor/luajit2/src/lualib.h"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) 2005-2023 Mike Pall."
SPDX-License-Identifier = "MIT"

# Source/data files that we can't comment in.
[[annotations]]
path = "testlist.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Fundament Software SPC <https://fundament.software>"
SPDX-License-Identifier = "Apache-2.0"

# Source/data files that we don't want to comment in.
[[annotations]]
path = [
	"**/*.alc",
	"test*.lua",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Fundament Software SPC <https://fundament.software>"
SPDX-License-Identifier = "Apache-2.0"

# Generated lock files.
[[annotations]]
path = "*.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Fundament Software SPC <https://fundament.software>"
SPDX-License-Identifier = "Apache-2.0"
