# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 Fundament Software SPC <https://fundament.software>

[toolchain]
channel = "stable"
components = ["rust-analyzer", "rust-src"]
targets = []
profile = "default"
