-- THIS FILE AUTOGENERATED BY terms-gen-meta.lua
---@meta "types.tuple_element_variant"

---@class (exact) tuple_element_variant: EnumValue
tuple_element_variant = {}

---@return boolean
function tuple_element_variant:is_element() end
---@return nil
function tuple_element_variant:unwrap_element() end
---@return boolean
function tuple_element_variant:as_element() end
---@return boolean
function tuple_element_variant:is_implicit() end
---@return nil
function tuple_element_variant:unwrap_implicit() end
---@return boolean
function tuple_element_variant:as_implicit() end
---@return boolean
function tuple_element_variant:is_trait() end
---@return nil
function tuple_element_variant:unwrap_trait() end
---@return boolean
function tuple_element_variant:as_trait() end

---@class (exact) tuple_element_variantType: EnumType
---@field define_enum fun(self: tuple_element_variantType, name: string, variants: Variants): tuple_element_variantType
---@field element tuple_element_variant
---@field implicit tuple_element_variant
---@field trait tuple_element_variant
return {}
